

CREATE DATABASE "Hrms"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Turkish_Turkey.1254'
    LC_CTYPE = 'Turkish_Turkey.1254'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

COMMENT ON DATABASE "HRMS"
    IS 'www.kodlama.io JAVA+REACT Kursu Ödevi';
	


CREATE TABLE public.users
(
	id SMALLINT NOT NULL GENERATED BY DEFAULT  AS IDENTITY (INCREMENT 1 START 1),
	email CHARACTER VARYING(100) NOT NULL,
	password CHARACTER VARYING(10) NOT NULL,
	CONSTRAINT PK_users PRIMARY KEY(id),
	CONSTRAINT UK_users_email UNIQUE (email)
);

CREATE TABLE public.staffs(
	userid SMALLINT NOT NULL,
	firstname CHARACTER VARYING(50) NOT NULL,
	surname CHARACTER VARYING(50) NOT NULL,
	CONSTRAINT PK_staffs PRIMARY KEY(userid),
	CONSTRAINT FK_staffs_users FOREIGN KEY(userid) REFERENCES public.users(id)
);

CREATE TABLE public.employees(
	userId SMALLINT  NOT NULL,
	firstname CHARACTER VARYING(50) NOT NULL,
	surname CHARACTER VARYING(50) NOT NULL,
	tcno CHARACTER VARYING(11) NOT NULL,
	birthdate DATE NOT NULL,
	CONSTRAINT PK_employees PRIMARY KEY(userid),
	CONSTRAINT FK_employees_users FOREIGN KEY(userid) REFERENCES public.users(id),
	CONSTRAINT UK_employees_tcno UNIQUE(tcno)

);

CREATE TABLE public.employers(
	userid SMALLINT  NOT NULL,
	companyname CHARACTER VARYING(50) NOT NULL,
	webaddress CHARACTER VARYING(50) NOT NULL,
	phoneno CHARACTER VARYING(10) NOT NULL,
	CONSTRAINT PK_employers PRIMARY KEY(userid),
	CONSTRAINT FK_wmployers_users FOREIGN KEY(userid) REFERENCES public.users(id),
	CONSTRAINT UK_employers_webaddress UNIQUE(webaddress)

);

CREATE TABLE public.email_verifications(
	userid SMALLINT  NOT NULL,
	codes CHARACTER VARYING(50) NOT NULL,
	isverified Boolean NOT NULL DEFAULT false,
	CONSTRAINT PK_email_verifications PRIMARY KEY(userid),
	CONSTRAINT FK_employers_users FOREIGN KEY(userid) REFERENCES public.users(id)


);

CREATE TABLE public.jobs(
	id SMALLINT  NOT NULL,
	userid SMALLINT  NOT NULL,
	title CHARACTER VARYING(200) NOT NULL,
	CONSTRAINT PK_jobs PRIMARY KEY(id),
	CONSTRAINT FK_jobs_users FOREIGN KEY(userid) REFERENCES public.users(id),
	CONSTRAINT UK_jobs_title UNIQUE(title)

);

CREATE TABLE public.employer_confirmations(
	employerid SMALLINT  NOT NULL,
	isconfirmated Boolean NOT NULL DEFAULT false,
	confirmatedbystaffid INTEGER NOT NULL,
	CONSTRAINT PK_employer_confirmations PRIMARY KEY(employerid),
	CONSTRAINT FK_employer_confirmations_employers FOREIGN KEY(employerid) REFERENCES public.employers(userid),
	CONSTRAINT FK_employer_confirmations_staffs FOREIGN KEY(confirmatedbystaffid) REFERENCES public.staffs(userid)
	

);

